#!/usr/bin/env python3

import sys
sys.path.append('lib')

from charmhelpers.core import hookenv
from charms.reactive import is_state
from charms.layer.apache_zeppelin import Zeppelin


def fail(msg):
    hookenv.action_fail(msg)
    sys.exit()


if not is_state('zeppelin.started'):
    fail('Zeppelin not yet ready')


zep = Zeppelin()
zep.stop()
zep.start()
